In [145]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [146]:
dataset= pd.read_csv("C:/Users/sanka/OneDrive/Desktop/dataset.csv")

In [147]:
dataset.head(5)

Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0     1           2   Female         45         152          63   
1     2           3   Female         50         157          50   
2     3           6   Female         47         150          47   
3     4           8     Male         45         172          65   
4     5           9   Female         46         155          65   

   Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                            161                              89   
1                            160                              93   
2                            101                              71   
3                            136                              93   
4                            123                              73   

   Heart Rate(b/m)  BMI(kg/m^2)  average segment value          Hypertension  \
0               97        27.27               0.953333  Stage 2 hypertension   
1               76        20.28               0.766667  Stage 2 hypertension   
2               79        20.89               0.603333                Normal   
3               87        21.97               0.893333       Prehypertension   
4               73        27.06               0.730000       Prehypertension   

       Diabetes     cerebral infarction     cerebrovascular disease  
0  Non-Diabetes  No cerebral infarction  No cerebrovascular disease  
1  Non-Diabetes  No cerebral infarction  No cerebrovascular disease  
2  Non-Diabetes  No cerebral infarction  No cerebrovascular disease  
3  Non-Diabetes  No cerebral infarction  No cerebrovascular disease  
4  Non-Diabetes  No cerebral infarction  No cerebrovascular disease

In [148]:
X = dataset.iloc[:, :-4].values
print(X)

[[1 2 'Female' ... 97 27.27 0.953333333]
 [2 3 'Female' ... 76 20.28 0.766666667]
 [3 6 'Female' ... 79 20.89 0.603333333]
 ...
 [217 417 'Male' ... 72 17.76 1.273333333]
 [218 418 'Male' ... 67 21.05 0.963333333]
 [219 419 'Male' ... 65 18.94 0.98]]


In [160]:
y = dataset.iloc[:, -3].values
print(y)

['Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Type 2 Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes' 'Non-Diabetes'
 'Non-Diabetes' 'Non-

## Encoding categorical columns

In [161]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])  # for gender column 
X           #0 for female 1 for male

array([[1, 2, 0, ..., 97, 27.27, 0.953333333],
       [2, 3, 0, ..., 76, 20.28, 0.766666667],
       [3, 6, 0, ..., 79, 20.89, 0.603333333],
       ...,
       [217, 417, 1, ..., 72, 17.76, 1.273333333],
       [218, 418, 1, ..., 67, 21.05, 0.963333333],
       [219, 419, 1, ..., 65, 18.94, 0.98]], dtype=object)

In [162]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [163]:
X_train

array([[195, 248, 0, ..., 67, 24.65, 0.493333333],
       [5, 9, 0, ..., 73, 27.06, 0.73],
       [216, 416, 0, ..., 79, 19.31, 0.97],
       ...,
       [118, 161, 1, ..., 82, 20.2, 0.86],
       [48, 63, 0, ..., 62, 22.6, 0.95],
       [173, 223, 1, ..., 66, 35.34, 0.623333333]], dtype=object)

In [164]:
X_test

array([[153, 201, 0, 65, 165, 72, 143, 77, 63, 26.45, 0.723333333],
       [75, 108, 1, 58, 160, 65, 137, 65, 72, 25.39, 0.68],
       [72, 105, 0, 86, 161, 70, 130, 66, 69, 27.01, 0.77],
       [162, 212, 1, 71, 155, 47, 159, 86, 62, 19.56, 0.63],
       [163, 213, 1, 63, 169, 62, 151, 91, 55, 21.71, 0.913333333],
       [144, 191, 0, 50, 163, 87, 110, 75, 78, 32.74, 1.06],
       [64, 95, 0, 64, 163, 72, 153, 71, 59, 27.1, 1.023333333],
       [154, 203, 0, 63, 153, 54, 123, 62, 52, 23.07, 0.943333333],
       [219, 419, 1, 24, 175, 58, 108, 68, 65, 18.94, 0.98],
       [136, 182, 0, 67, 156, 56, 113, 55, 61, 23.01, 0.85],
       [150, 198, 1, 54, 155, 82, 157, 94, 76, 34.13, 1.07],
       [6, 10, 0, 48, 160, 68, 124, 62, 70, 26.56, 0.523333333],
       [91, 128, 1, 73, 160, 62, 123, 68, 67, 24.22, 0.876666667],
       [169, 219, 1, 59, 165, 68, 149, 92, 78, 24.98, 0.97],
       [203, 259, 0, 84, 152, 44, 127, 65, 60, 19.04, 0.626666667],
       [192, 245, 1, 54, 170, 60, 137, 80, 81

In [165]:
y_train

array(['Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Type 2 Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Type 2 Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', '

In [166]:
y_test 

array(['Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Type 2 Diabetes', 'Type 2 Diabetes',
       'Type 2 Diabetes', 'Type 2 Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Type 2 Diabetes', 'Non-Diabetes', 'Non-Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Type 2 Diabetes',
       'Type 2 Diabetes', 'Type 2 Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Non-Diabetes', 'Type 2 Diabetes', 'Non-Diabetes',
       'Non-Diabetes', 'Type 2 Diabetes'

In [167]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [168]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [1]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

NameError: name 'classifier' is not defined

In [170]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[44  0]
 [ 1 10]]


0.9818181818181818